// Code generated by goctl. DO NOT EDIT.
package types

type FeedHandlerRequest struct {
	LastestTime int64  `json:"LastestTime"`
	Token       string `json:"Token"`
}

type FeedHandlerResponse struct {
	StatusCode int32  `json:"StatusCode""`
	StatusMsg  string `json:"StatusMsg"`
	VideoList  Video  `json:"VideoList"`
	NextTime   int64  `json:""NextTime"`
}

type Video struct {
	Id            int64  `json:"Id"`
	Author        User   `json:"Author"`
	PlayUrl       string `json:"PlayUrl"`
	CoverUrl      string `json:"CoverUrl"`
	FavoriteCount int64  `json:"FavoriteCount"`
	CommentCount  int64  `json:"CommentCount"`
	IsFavotite    bool   `json:"IsFavotite"`
	Title         string `json:"Title"`
}

type User struct {
	Id            int64  `json:"Id"`
	Name          string `json:"Name"`
	FollowCount   string `json:"FollowCount"`
	FollowerCount string `json:"FollowerCount"`
	IsFollow      string `json:"IsFollow"`
}

type UserRegisterHandlerRequest struct {
	UserName string `json:"UserName"`
	PassWord string `json:"PassWord"`
}

type UserRegisterHandlerResponse struct {
	StatusCode int32  `json:"StatusCode"`
	StatusMsg  string `json:"StatusMsg"`
	UserID     int64  `json:"UserID"`
	Token      string `json:"token"`
}

type UserloginHandlerRequest struct {
	StatusCode int32 `json:"StatusCode"`
}

type UserloginHandlerResponse struct {
	UserName string `json:"UserName"`
}

type UserHandlerRequest struct {
	StatusCode int32 `json:"StatusCode"`
}

type UserHandlerResponse struct {
	UserName string `json:"UserName"`
}

type PublishActionHandlerRequest struct {
	Token string `json:"Token"`
	Data  int32  `json:"Data"` // 存疑bytes
	Title string `json:"Title"`
}

type PublishActionHandlerResponse struct {
	StatusCode string `json:"UserName"`
	StatusMsg  string `json:"StatusMsg"`
}

type PublishListHandlerRequest struct {
	StatusCode int32 `json:"StatusCode"`
}

type PublishListHandlerResponse struct {
	StatusCode string `json:"UserName"`
	StatusMsg  string `json:"StatusMsg"`
}

type CommmentActionHandlerRequest struct {
	StatusCode int32 `json:"StatusCode"`
}

type CommmentActionHandlerResponse struct {
	StatusCode string `json:"UserName"`
	StatusMsg  string `json:"StatusMsg"`
}

type CommmentListHandlerRequest struct {
	StatusCode int32 `json:"StatusCode"`
}

type CommmentListHandlerResponse struct {
	StatusCode string `json:"UserName"`
	StatusMsg  string `json:"StatusMsg"`
}

type RelationActionHandlerRequest struct {
	StatusCode int32 `json:"StatusCode"`
}

type RelationActionHandlerResponse struct {
	StatusCode string `json:"UserName"`
	StatusMsg  string `json:"StatusMsg"`
}

type RelationFollowListHandlerRequest struct {
	StatusCode int32 `json:"StatusCode"`
}

type RelationFollowListHandlerResponse struct {
	StatusCode string `json:"UserName"`
	StatusMsg  string `json:"StatusMsg"`
}

type RelationFollowerListHandlerRequest struct {
	StatusCode int32 `json:"StatusCode"`
}

type RelationFollowerListHandlerResponse struct {
	StatusCode string `json:"UserName"`
	StatusMsg  string `json:"StatusMsg"`
}
