MySQL:
 UserName: SimpleTikTok
 PassWord: CYchp8jJePjnS5HF  # 404NotFound MD5 32位小写
 Host: 122.9.98.17
 Port: 3306
 DBname: simpletiktok
 TimeOut: 10s

Minio:
 Endpoint: 39.106.72.165:9001 # 用的API端口，不是Console
 AccessKeyID: minio
 SecretAccessKey: minio123
 UseSSL: false

  

gormpool:
 MaxIdleConns: 25
 MaxOpenConns: 25
 ConnMaxLifetime: 5