// Code generated by goctl. DO NOT EDIT.
// Source: utilserver.proto

package utilserverclient

import (
	"context"

	"SimpleTikTok/internal_proto/microservices/utilserver/types/utilserver"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetSnapshotRequest  = utilserver.GetSnapshotRequest
	GetSnapshotResponse = utilserver.GetSnapshotResponse

	Utilserver interface {
		// 通过ffmpeg来截图
		GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error)
	}

	defaultUtilserver struct {
		cli zrpc.Client
	}
)

func NewUtilserver(cli zrpc.Client) Utilserver {
	return &defaultUtilserver{
		cli: cli,
	}
}

// 通过ffmpeg来截图
func (m *defaultUtilserver) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error) {
	client := utilserver.NewUtilserverClient(m.cli.Conn())
	return client.GetSnapshot(ctx, in, opts...)
}
